baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'JasPlay3D'
theme = "ananke"

[params]
hero = "/images/Desserts1.png"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/channel/UCAa8ZTFcJoVtgrk2dEkAXSA"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/jasplay3d/"

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com"
