baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'JasPlay3D'
theme = "ananke"

[params]
hero = "/images/Desserts1.png"

[markup.goldmark.renderer]
  unsafe = true

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com"
