baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'JasPlay3D'
theme = "ananke"

[params]
hero = "/images/Desserts1.png"


[markup.goldmark.renderer]
  unsafe = true

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/channel/UCAa8ZTFcJoVtgrk2dEkAXSA"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/jasplay3d/"

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/profile.php?id=61550288742828&mibextid=ZbWKwL"

[[params.ananke_socials]]
name = "twitter"
url = "ttps://twitter.com/JasPlay3D?t=M2OdFlb_5Z9Xqhh2b1FjYA&s=08"
